server:
  port: 8081


# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.xmutca: info
  file:
    path: logs
    name: ${spring.application.name}-log


spring:
  redis:
    host: localhost
    port: 6379
  boot:
    admin:
      client:
        username: root
        password: root


xxl:
  job:
    app-name: xmutca-incubator-snowflake
    port: 9090
    registries: http://localhost:8080/xxl-job-admin

system:
  generator:
    snowflake:
      data-center-id: 10
