server:
  port: 0 # 线上环境要写死，方便docker expose



# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

feign:
  hystrix:
    enabled: true
