server:
  port: 8189


# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  file: logs/${spring.application.name}-log
  level:
    com.xmutca: info

system:
  generator:
    type: snowflake
    snowflake:
      worker_id: 0
      data_centerId: 0

spring:
  boot:
    admin:
      client:
        username: root
        password: root
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.199.150:53366/xmutca-incubator-auth?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*/**.xml

pagehelper:
  helperDialect: mysql

