server:
  port: 8081


# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  file: logs/${spring.application.name}-log
  level:
    com.xmutca: info

system:
  generator:
    type: snowflake
    snowflake:
      worker_id: 0
      data_centerId: 0

spring:
  boot:
    admin:
      client:
        username: root
        password: root
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/xmutca-incubator-member?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*/**.xml

pagehelper:
  helperDialect: mysql

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379

