server:
  port: 9898


# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

feign:
  hystrix:
    enabled: false
  sentinel:
    enabled: true


logging:
  file: logs/${spring.application.name}-log
  level:
    com.xmutca: info

spring:
  boot:
    admin:
      client:
        username: root
        password: root
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
