server:
  port: 8686

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


logging:
  file: logs/${spring.application.name}-log
  level:
    com.xmutca: info